2025-09-20 19:04:52,113 INFO    MainThread:3599813 [wandb_setup.py:_flush():68] Current SDK version is 0.19.6
2025-09-20 19:04:52,113 INFO    MainThread:3599813 [wandb_setup.py:_flush():68] Configure stats pid to 3599813
2025-09-20 19:04:52,113 INFO    MainThread:3599813 [wandb_setup.py:_flush():68] Loading settings from /users/pmahable/.config/wandb/settings
2025-09-20 19:04:52,116 INFO    MainThread:3599813 [wandb_setup.py:_flush():68] Loading settings from /oscar/data/larschan/shared_data/BindGPS/model/wandb/settings
2025-09-20 19:04:52,117 INFO    MainThread:3599813 [wandb_setup.py:_flush():68] Loading settings from environment variables
2025-09-20 19:04:52,118 INFO    MainThread:3599813 [wandb_init.py:setup_run_log_directory():637] Logging user logs to /oscar/data/larschan/shared_data/BindGPS/model/wandb/run-20250920_190452-2li3hu88/logs/debug.log
2025-09-20 19:04:52,119 INFO    MainThread:3599813 [wandb_init.py:setup_run_log_directory():638] Logging internal logs to /oscar/data/larschan/shared_data/BindGPS/model/wandb/run-20250920_190452-2li3hu88/logs/debug-internal.log
2025-09-20 19:04:52,121 INFO    MainThread:3599813 [wandb_init.py:monkeypatch_ipython():589] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7f1861b02980>
2025-09-20 19:04:52,122 INFO    MainThread:3599813 [wandb_init.py:init():756] calling init triggers
2025-09-20 19:04:52,123 INFO    MainThread:3599813 [wandb_init.py:init():761] wandb.init called with sweep_config: {}
config: {'learning_rate': 0.02, 'architecture': 'CNN', 'dataset': 'CIFAR-100', 'epochs': 10, '_wandb': {}}
2025-09-20 19:04:52,124 INFO    MainThread:3599813 [wandb_init.py:init():789] starting backend
2025-09-20 19:04:52,583 INFO    MainThread:3599813 [wandb_init.py:init():793] sending inform_init request
2025-09-20 19:04:52,612 INFO    MainThread:3599813 [backend.py:_multiprocessing_setup():97] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2025-09-20 19:04:52,612 INFO    MainThread:3599813 [wandb_init.py:init():808] backend started and connected
2025-09-20 19:04:52,615 INFO    MainThread:3599813 [wandb_run.py:_label_probe_notebook():1196] probe notebook
2025-09-20 19:04:52,616 INFO    MainThread:3599813 [wandb_init.py:init():901] updated telemetry
2025-09-20 19:04:52,650 INFO    MainThread:3599813 [wandb_init.py:init():936] communicating run to backend with 90.0 second timeout
2025-09-20 19:04:53,083 INFO    MainThread:3599813 [wandb_init.py:init():994] starting run threads in backend
2025-09-20 19:04:53,937 INFO    MainThread:3599813 [wandb_run.py:_console_start():2385] atexit reg
2025-09-20 19:04:53,938 INFO    MainThread:3599813 [wandb_run.py:_redirect():2235] redirect: wrap_raw
2025-09-20 19:04:53,939 INFO    MainThread:3599813 [wandb_run.py:_redirect():2300] Wrapping output streams.
2025-09-20 19:04:53,939 INFO    MainThread:3599813 [wandb_run.py:_redirect():2325] Redirects installed.
2025-09-20 19:04:53,950 INFO    MainThread:3599813 [wandb_init.py:init():1036] run started, returning control to user process
2025-09-20 19:04:53,951 INFO    MainThread:3599813 [wandb_run.py:_finish():2110] finishing run bind-gps/basic-intro/2li3hu88
2025-09-20 19:04:53,952 INFO    MainThread:3599813 [jupyter.py:save_history():458] not saving jupyter history
2025-09-20 19:04:53,953 INFO    MainThread:3599813 [jupyter.py:save_ipynb():386] not saving jupyter notebook
2025-09-20 19:04:53,953 INFO    MainThread:3599813 [wandb_init.py:_jupyter_teardown():571] cleaning up jupyter logic
2025-09-20 19:04:53,954 INFO    MainThread:3599813 [wandb_run.py:_atexit_cleanup():2350] got exitcode: 0
2025-09-20 19:04:53,956 INFO    MainThread:3599813 [wandb_run.py:_restore():2332] restore
2025-09-20 19:04:53,957 INFO    MainThread:3599813 [wandb_run.py:_restore():2338] restore done
2025-09-20 19:04:55,669 INFO    MainThread:3599813 [wandb_run.py:_footer_history_summary_info():3963] rendering history
2025-09-20 19:04:55,670 INFO    MainThread:3599813 [wandb_run.py:_footer_history_summary_info():3995] rendering summary
2025-09-20 19:04:55,672 INFO    MainThread:3599813 [wandb_run.py:_footer_sync_info():3924] logging synced files
